name: Test & Build (1.19.2)
on:
  push:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Setup Spigot
        uses: SpraxDev/Action-SpigotMC@v4.0.0
        with:
          versions: 1.19.2
          remapped: true
          generateSrc: false
          generateDoc: false
          disableJavaCheck: false
          buildToolProvider: SpigotMC
      - name: Build & Test
        run: mvn -pl core,1.19.2 -am clean package
